### ISSUE TITLE
Vine lenght

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#30]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Mosquera, V   |
| **Program** | CIP-Lima|

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Vine length    |
| **Definition**         | The main vine is measured at certain time-point     |
| **Trait Class**        | Morphological   |
| **Measurement Method** | The average length of of the main vine of representative plants per plot is measured.        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | cm           |

**Comment by dgemenet** [comment]
To be better defined

**Comment by dgemenet** [comment]
Re-defined
