### ISSUE TITLE
Vine diameter

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#31]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Mosquera, V    |
| **Program** | CIP-Lima |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Vine diameter    |
| **Definition**         | The diameter of the basal node of the main vine     |
| **Trait Class**        | Morphological   |
| **Measurement Method** | The average diameter of basal nodes measured on the main vine of representative plants per plot         |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | mm           |

**Comment by dgemenet** [comment]
To be better defined

**Comment by dgemenet** [comment]
Re-defined
