### ISSUE TITLE
Canopy temperature

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#33]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Mosquera, V    |
| **Program** | CIP-Lima |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Canopy temperature    |
| **Definition**         | The temperature of the canopy measured using an infrared thermometer     |
| **Trait Class**        | Physiological   |
| **Measurement Method** | The average recorded value of canopy temperature made by passing the infrared thermometer on canopies of representative plants per plot        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |Degrees centigrade           |

**Comment by dgemenet** [comment]
To be better defined

**Comment by dgemenet** [comment]
Re-defined
