### ISSUE TITLE
Leaf area

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#35]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Mosquera, V    |
| **Program** | CIP-Lima |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Leaf area    |
| **Definition**         | The leaf area measurement based on a number of representative leaves per plot    |
| **Trait Class**        | Morphological   |
| **Measurement Method** | Image analysis of pictures taken on representative mature leaves per plot. The picture taking should be under controlled conditions to avoid variations from one plot to the next.        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | mm2           |

**Comment by dgemenet** [comment]
To be better defined

**Comment by dgemenet** [comment]
Redefined
