### ISSUE TITLE
Pencil type root fresh weight

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#37]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Mosquera, V    |
| **Program** | CIP-Lima |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Pencil roots fresh weight    |
| **Definition**         | The weight of roots with diameter less than 5 mm     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | Weighing the total roots per plot with diameter less than 5 mm       |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | g           |

**Comment by dgemenet** [comment]
To be better defined

**Comment by dgemenet** [comment]
Redefined
